server.port=3000
spring.application.name=spring-boot

# import contents from .env file
spring.config.import=optional:file:.env[.properties]

rest_client_canvas.api_token = ${CANVAS_API_TOKEN}
rest_client_canvas.base_url = ${CANVAS_BASE_URL}